/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/documentations/{documentation_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_documentations__documentation_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documentations/{documentation_id}/documents/{document_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documentations__documentation_id__documents__document_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documentations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documentations */
        get: operations["list_documentations_api_documentations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documentations{documentation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Documentation */
        delete: operations["delete_documentation_api_documentations_documentation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate/{documentation_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Documentation Progress */
        get: operations["get_documentation_progress_api_generate__documentation_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Documentation */
        post: operations["generate_documentation_api_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/output_languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Output Languages */
        get: operations["get_output_languages_api_metadata_output_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/supported_platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supported Platforms */
        get: operations["get_supported_platforms_api_metadata_supported_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DocumentResponse */
        DocumentResponse: {
            /** Document Name */
            document_name: string;
            /** Content */
            content: string;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "draft" | "approved";
        /** DocumentSummary */
        DocumentSummary: {
            /** Document Name */
            document_name: string;
            /** Goal */
            goal: string;
            /** @default draft */
            status: components["schemas"]["DocumentStatus"];
            /**
             * Review
             * @default
             */
            review: string;
            /**
             * Iteration
             * @default 0
             */
            iteration: number;
            /**
             * Source Node Ids
             * @default []
             */
            source_node_ids: string[];
        };
        /** DocumentationSummary */
        DocumentationSummary: {
            /** Documentation Id */
            documentation_id: string;
            /** Documentation Name */
            documentation_name: string;
            /** Additional Name */
            additional_name: string | null;
            /**
             * Fetched Date
             * Format: date-time
             */
            fetched_date: string;
            /** Input Token Used */
            input_token_used: number;
            /** Output Token Used */
            output_token_used: number;
        };
        /** GenerationRequest */
        GenerationRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            platform: components["schemas"]["SupportedPlatform"];
            /** Access Token */
            access_token?: string | null;
            /** Iteration */
            iteration: number;
            output_language: components["schemas"]["OutputLanguage"];
        };
        /** GenerationResponse */
        GenerationResponse: {
            /** Documentation Id */
            documentation_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OutputLanguage
         * @enum {string}
         */
        OutputLanguage: "fr" | "en";
        /** OutputLanguageResponse */
        OutputLanguageResponse: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /**
         * SupportedPlatform
         * @enum {string}
         */
        SupportedPlatform: "GitLab" | "GitHub";
        /** SupportedPlatformResponse */
        SupportedPlatformResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_documents_api_documentations__documentation_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documentations__documentation_id__documents__document_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentation_id: string;
                document_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documentations_api_documentations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentationSummary"][];
                };
            };
        };
    };
    delete_documentation_api_documentations_documentation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_documentation_progress_api_generate__documentation_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_documentation_api_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_output_languages_api_metadata_output_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputLanguageResponse"][];
                };
            };
        };
    };
    get_supported_platforms_api_metadata_supported_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportedPlatformResponse"][];
                };
            };
        };
    };
}
